Feature dnd vertical
NilsHolthey/capstone-project pull request #24
Opened 2022-05-27 14:14 UTC by NilsHolthey

With this PR I implemented the drag and drop feature. I had to do a lot of refactoring an implementing Zustand.
I think it is good for now. Because i need time to work on other features, I will leave it like it is( despite the repetitions).
Userstory: https://github.com/NilsHolthey/capstone-project/issues/17

2022-05-28 10:55 UTC, UrsulaMontag commented on src/components/Todos/Todo.js
>  }
look at my previously made comment.

2022-05-28 10:55 UTC, UrsulaMontag commented on src/components/UI/Dropzone/Dropzone.styled.js
> +`;
Maybe you want to use a more semantic tag than div. I would suggest to use 'section' or 'article'

2022-05-28 10:55 UTC, UrsulaMontag commented on src/components/UI/Footer/StyledFooter.styled.js
>  	position: fixed;
Semantically, footer is not quite correct here. what you're actually styling is a navigation to your add-form. I'd rethink renaming the whole component to 'navigation'. A footer is actually something else. but that's just meant as a tip here and in the course we always solved it the way you do it here.
But in any case you should make a 'styled.nav' out of 'styled.footer'.

2022-05-28 10:55 UTC, UrsulaMontag commented on src/lib/useStore.js
> +					};
I would also add here still 'produce' from immer and edit a draft of your states

2022-05-28 10:55 UTC, UrsulaMontag commented on src/lib/useStore.js
> +			moveOneUp: index => {
If you use immer-hook and produce, I would name the state something like 'draft' or 'copyOfState'. Then you'll never forget what 'produce' is doing for you.

2022-05-28 10:55 UTC, UrsulaMontag commented on src/services/get-didIts.js
> +};
Do you need the get-services anymore anywhere in your code? You have the same data in your useStore. ;-)

2022-05-30 13:00 UTC, aclaes requested changes
There is a lot of redundant logic in the “Todos” components, the “Dropzone” component and the store. This violates the DRY principle (don’t repeat yourself). 

The work to create this code was probably more complex than it could have been. This will also be true for every change that needs to be done.

Let’s talk about some ideas do refactor your code.

2022-05-31 07:26 UTC, NilsHolthey commented
Thank you Ursula and thank you Alex, 
I made some changes.

2022-05-31 10:20 UTC, aclaes commented on src/lib/useStore.js
> +			moveOneUp: index => {
Ok 👍

2022-05-31 10:21 UTC, aclaes commented on src/lib/useStore.js
> +					};
Ok 👍 

Your code uses `push()` know, which will add to the end of the list, instead of the beginning (like before). I hope you are aware of this.

2022-05-31 10:22 UTC, aclaes commented on src/components/UI/Footer/StyledFooter.styled.js
>  	position: fixed;
Ok 👍

2022-05-31 10:23 UTC, aclaes commented on src/components/UI/Dropzone/Dropzone.styled.js
> +`;
I think `div` is okay in this situation. `section` or `article` would not reflect the dropzone content and meaning

2022-05-31 10:24 UTC, aclaes commented on src/components/Todos/DoingIt.js
> +}
Looks good to me after some refactoring

2022-05-31 10:25 UTC, aclaes commented on src/components/Dropzones/Dropzone1.js
> +}
Ok 👍

2022-05-31 10:25 UTC, aclaes commented on src/components/Dropzones/Dropzone2.js
> +}
After refactoring this file doesn't exist any more

2022-05-31 10:33 UTC, aclaes commented on src/components/Todos/Todo.js
>  }
Looks good to me after some refactoring

2022-05-31 10:38 UTC, aclaes requested changes

2022-05-31 10:38 UTC, aclaes commented on src/services/get-doingIts.js
> +export const getDoingIts = () => {
I think the services and the static data in `.json` files can be deleted.

2022-05-31 12:26 UTC, aclaes approved these changes

2022-05-31 12:46 UTC, merged