Feature overview
NilsHolthey/capstone-project pull request #29
Opened 2022-06-01 09:22 UTC by NilsHolthey

With this PR I create an overview page:

Userstory: https://github.com/NilsHolthey/capstone-project/issues/25

2022-06-01 13:55 UTC, anitaschiller requested changes
Hi Nils, pretty cool and quite complex (including your styled-components). Did not find much to comment on, but some smaller stuff 😉.

2022-06-01 13:55 UTC, anitaschiller commented on src/components/Overview/OverviewGrid.js
> +		(lengthOfTodos / (lengthOfTodos + legthOfDoingIts + lengthOfDidIts)) * 100
Why don't you use `sumOfArrays` (or `sumOfTasks` if you decide to change it)?

```suggestion
		(lengthOfTodos / sumOfArrays) * 100
```

2022-06-01 13:55 UTC, anitaschiller commented on src/components/Overview/PercentageOverview.js
> +	const dash = (progress * circumference) / 100;
Maybe I missed sth but I don't think you need the `useState` and `useEffect`: 

```suggestion
	const viewBox = `0 0 ${size} ${size}`;
	const radius = (size - strokeWidth) / 2;
	const circumference = radius * Math.PI * 2;
	const dash = (percentage * circumference) / 100;
```

2022-06-01 14:40 UTC, NilsHolthey commented
Thank you Anita, I made some changes...

2022-06-02 07:00 UTC, anitaschiller approved these changes
Looks good to me :)

2022-06-02 08:05 UTC, merged